a = set(["Jake", "John", "Jack"])
b = set(["Jill", "John"])
print(a)
print(b)

print(a.intersection(b))
print(b.intersection(a))
print(a.symmetric_difference(b))
print(b.symmetric_difference(a))
print(a.difference(b))
print(b.difference(a))
print(a.union(b))